# Site settings
title: Martin Seeler
email: blog@chasmo.de
description: "About Java and beyond"
baseurl: ""
url: "http://martinseeler.github.io"
twitter_username: Chasmo90
github_username:  MartinSeeler
timezone: "Europe/Berlin"
lsi: false

# Build settings
markdown: kramdown
kramdown:
  input: GFM
#redcarpet:
#  extensions: ["smart", "tables", "no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]
permalink: "/:categories/:title.html"
safe: true
exclude: ["bower_components/", "node_modules/", "package.json", "bower.json", "Gulpfile.*", "LICENSE", "README.md"]


