# Site settings
title: Martin Seeler
email: blog@chasmo.de
description: "About programming and trading"
baseurl: ""
url: "http://www.martinseeler.com"
twitter_username: Chasmo90
github_username:  MartinSeeler
timezone: "Europe/Berlin"
lsi: false

# Build settings
markdown: kramdown
kramdown:
  input: GFM
permalink: "/:title.html"
safe: true
exclude: ["bower_components/", "node_modules/", "package.json", "bower.json", "Gulpfile.*", "LICENSE", "README.md"]


